environment:
  - PORT=5000
services:
  web:
    image: kaiomagalhaes/roadrunner:<IMAGE_TAG_VERSION>
    port: 5000
    environment:
      - DATABASE_URL
      - LOG_ENV
      - LOG_HOST
      - AZURE_AUTH_KEY
      - GIT_AUTH_KEY
      - JIRA_AUTH_KEY
      - SLACK_API_KEY
      - SLACK_API_URL
    domain: api.roadrunner.codelitt.dev