resources:
  database:
    type: postgres
  redis:
    type: redis

services:
  roadrunner-api:
    build: .
    port: 3000
    domain: ${HOST}
    resources:
      - database
      - redis
    environment:
      - LOG_ENV=
      - LOG_HOST=
      - AZURE_AUTH_KEY
      - GIT_AUTH_KEY
      - JIRA_AUTH_KEY
      - NOTIFICATIONS_API_KEY
      - NOTIFICATIONS_API_URL
      - ENVIRONMENT=development
      - SECRET_KEY_BASE=no-value
  worker:
    build: .
    command: bundle exec sidekiq
    resources:
      - redis

timers:
  servers-verification:
    command: rake server:check_up_servers
    schedule: "* * * * *"
    service: roadrunner-api

  update-sprint-data:
    command: rake sprints:update_sprints_state_azure
    schedule: "0 * * * *"
    service: roadrunner-api