resources:
  database:
    type: postgres
  redis:
    type: redis

services:
  api:
    build: .
    port: 3000
    resources:
      - database
      - redis
    environment:
      - LOG_ENV=
      - LOG_HOST=
      - AZURE_AUTH_KEY
      - GIT_AUTH_KEY
      - JIRA_AUTH_KEY
      - SLACK_API_KEY
      - SLACK_API_URL
      - ENVIRONMENT=development
      - SECRET_KEY_BASE=no-value
    domain: api.roadrunner.codelitt.dev
  worker:
    build: .
    command: bundle exec sidekiq
    resources:
      - database
      - redis

timers:
  servers-verification:
    command: rake server:check_up_servers
    schedule: "* * * * *"
    service: api