resources:
  database:
    type: postgres
services:
  api:
    build: .
    port: 3000
    resources:
      - database
    environment:
      - LOG_ENV
      - LOG_HOST
      - AZURE_AUTH_KEY
      - GIT_AUTH_KEY
      - JIRA_AUTH_KEY
      - SLACK_API_KEY
      - SLACK_API_URL
    domain: ${HOST}
timers:
  servers-verification:
    command: rake server:check_up_servers
    schedule: "* * * * *"
    service: api