version: '2'
services:
  db:
    image: postgres
    container_name: roadrunner-db
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - '5432:5432'

  redis:
    container_name: roadrunner-redis
    image: "redis:alpine"
    ports:
      - '6379:6379'

  app:
    container_name: roadrunner-api
    tty: true
    stdin_open: true
    build:
      context: .
      target: development

    volumes:
      - .:/app

    env_file:
      - .env

    ports:
      - '3000:3000'

    depends_on:
      - db
      - box
      - redis

    links:
      - db
      - box
      - redis

  box:
    container_name: roadrunner-bundle-box
    image: busybox
    volumes:
      - /box
