ping_servers:
  cron: "* * * * *"
  class: "PingServersWorker"
  queue: default

remove_flows:
  cron: "0 * * * *"
  class: "RemoveFlowsWorker"
  queue: default

pull_request_comments:
  cron: "0 * * * *"
  class: "UpdatePullRequestsCommentsWorker"
  queue: default

ping_afinium_servers:
  cron: "*/5 * * * *"
  class: "PingAfiniumServersWorker"
  queue: default
