jira:
  cron: "0 22 * * *"
  class: "JiraDataLoaderWorker"
  queue: default

ping_servers:
  cron: "* * * * *"
  class: "PingServersWorker"
  queue: default

remove_flows:
  cron: "0 * * * *"
  class: "RemoveFlowsWorker"
  queue: default

content_notion:
  cron: "0 0 12 1 1"
  class: "ContentNotionWorker"
  queue: default
