azure:
  cron: "0 23 * * *"
  class: "AzureDataLoaderWorker"
  queue: default

jira:
  cron: "0 22 * * *"
  class: "JiraDataLoaderWorker"
  queue: default

ping_servers:
  cron: "* * * * *"
  class: "PingServersWorker"
  queue: default