name: DEV DEPLOY

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: postgres
  POSTGRES_HOST: localhost
  RAILS_ENV: test
  SLACK_API_URL: https://slack-api.codelitt.dev

on:
  push:
    branches: [ '*/*' ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-ruby@v1

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run RSpec
        run: COVERAGE=true bundle exec rspec

  deploy-dev:
    needs: test-and-lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.2.6
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DEV }}
        buildpack: # optional
        branch: 'master'
        dontuseforce: false
        usedocker: # optional, default is false
        docker_heroku_process_type: # optional, default is web
        appdir: # optional, default is
        healthcheck: # optional, default is
        checkstring: # optional, default is
        procfile: # optional, default is
        steps:

    - name: Notify deployment
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.roadrunner.codelitt.dev/flows?deploy_type=deploy-notification&host=api.roadrunner.codelitt.dev&env=qa'
        method: 'POST'
