name: PROD DEPLOY

on:
  push:
    tags: [ 'v*' ]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set release version
      run: echo "RELEASE_VERSION=$GITHUB_REF" >> $GITHUB_ENV

    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.2.6
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_PROD }}
        branch: ${{ env.RELEASE_VERSION }}
        dontuseforce: false
  build-and-deploy-to-convox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: test
      run: echo $GITHUB_REF

    - name: Set tag version
      run: echo "TAG_VERSION=\"$(echo $GITHUB_REF | sed 's/.*tags\///')\"" >> $GITHUB_ENV

    - name: Set image name
      run: echo "IMG_NAME=kaiomagalhaes/roadrunner:${{env.RELEASE_VERSION}}" >> $GITHUB_ENV

    - name: Build image with webpack
      uses: dfreilich/pack-action@v1
      with:
        args: 'build ${{ env.IMG_NAME }} --path /github/workspace/ --builder heroku/buildpacks:20 --publish'
        username: kaiomagalhaes
        password: ${{ secrets.DOCKER_PASS }}

    - name: Updates the image name in convox.yml
      run: sed -i -e "s/<IMAGE_TAG_VERSION>/${{env.RELEASE_VERSION}}/g" convox.yml

    - uses: convox/action-deploy@v1
      name: Deploy to Convox
      with:
        rack: prod
        app: roadrunner
        password: ${{ secrets.CONVOX_DEPLOY_KEY }}
