name: PROD DEPLOY

on:
  push:
    tags: [ 'v*' ]

jobs:
  build-and-deploy-to-convox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: convox/action-deploy@v1
      name: Deploy to Convox
      with:
        rack: prod
        app: roadrunner
        password: ${{ secrets.CONVOX_DEPLOY_KEY }}
