name: QA DEPLOY

on:
  push:
    tags: [ 'rc.*' ]

jobs:
  deploy-convox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: convox/action-deploy@v1
      name: Deploy to Convox
      with:
        rack: qa-roadrunner
        app: roadrunner
        password: ${{ secrets.CONVOX_DEPLOY_KEY }}

    - name: Notify deployment
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.roadrunner.codelitt.dev/flows?deploy_type=deploy-notification&host=api.roadrunner.codelitt.dev&env=qa'
        method: 'POST'